package cage.core.input.component;

public enum Key implements IInputComponent {
    NONE,
    ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, INSERT, PRINT_SCREEN, PAUSE,
    GRAVE, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, MINUS, EQUALS, BACKSPACE, HOME, END, NUMLOCK, NUMPAD_DIVIDE, NUMPAD_MULTIPLY, NUMPAD_SUBTRACT,
    TAB, Q, W, E, R, T, Y, U, I, O, P, LBRACKET, RBRACKET, BACKSLASH, DELETE, PAGEUP, NUMPAD7, NUMPAD8, NUMPAD9, NUMPAD_ADD,
    CAPSLOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, APOSTROPHE, ENTER, PAGEDOWN, NUMPAD4, NUMPAD5, NUMPAD6,
    LSHIFT, Z, X, C, V, B, N, M, COMMA, PERIOD, SLASH, RSHIFT, UP, NUMPAD1, NUMPAD2, NUMPAD3, NUMPAD_ENTER,
    LCONTROL, LALT, SPACE, RALT, RCONTROL, LEFT, DOWN, RIGHT, NUMPAD0, NUMPAD_DECIMAL
}
