package cage.core.graphics.type;

public enum BlendType {
    ZERO, ONE,
    SRC_COLOR, INV_SRC_COLOR,
    SRC_ALPHA, INV_SRC_ALPHA,
    DEST_ALPHA, INV_DEST_ALPHA,
    DEST_COLOR, INV_DEST_COLOR,
    BLEND_FACTOR, INV_BLEND_FACTOR,
    SRC1_COLOR, INV_SRC1_COLOR,
    SRC1_ALPHA, INV_SRC1_ALPHA;
}
